### ISSUE TITLE
translate to Russian

### ISSUE THREAD

**Issue by TitanNano** [TitanNano/TS4ControlAnySim#10]
There is currently no Russian translation. The following strings have to b translated:

1. Control Sim
2. Don't Control Sim
3. You are currently running ControlAnySim Version {0.String}, which is an experimental preview version! Experimental versions are not intended for normal players, but for testing bug fixes and new features! If you didn't install this version on purpose, you should not use it!
4. Quit Game
5. I know what I'm doing
6. Control Any Sim WARNING

**Comment by yltme** [comment]
1. Управлять Симом
2. Перестать управлять Симом
3. Сейчас Вы используете Управляй Любым Симом версии {0.String}, являющейся экспериментальной версией предварительного просмотра! Экспериментальные версии предназначены не для обычных игроков, а для тестирования новых функций и исправления ошибок! Если Вы не устанавливали эту версию намеренно, не используйте ее!
4. Выйти из игры
5. Я знаю, что делаю
6. ПРЕДУПРЕЖДЕНИЕ Управляй Любым Симом
If you like, you can leave the name of the mod in English (Control Any Sim - Управляй Любым Симом)

**Comment by TitanNano** [comment]
> If you like, you can leave the name of the mod in English (Control Any Sim - Управляй Любым Симом)

@yltme what do you think is more convenient for players? When I translate to German I leave thee English title of the mod, but that might not fit for other languages. If you are a native speaker, I think you know best.

**Comment by yltme** [comment]
I think it's better to translate the title into Russian - Управляй любым Симом

**Comment by TitanNano** [comment]
Translation should be available in this pre-release version. https://github.com/TitanNano/TS4ControlAnySim/releases/tag/v1.2.0-pre.3
