### ISSUE TITLE
MCCC says the mod is broken. Is this true or is it normal? No module named 'control_any_sim.ui'

### ISSUE THREAD

**Issue by vpuhoff** [TitanNano/TS4ControlAnySim#102]
Exception Date: 2024-06-23 23:03:40  
Game Version: 1.107.112.1030-1.200.000.625.Release  
Category ID: utils.py:120
Recommended Action  You have a bad script mod. It may be out of date or broken. Check with the creator for an update or remove the mod listed.
ControlAnySim.ts4script
**Reason**  The listed script mod failed to load and should be removed or updated. 
**Failure:** 'control_any_sim/ui' (control_any_sim.ui) No module named 'control_any_sim.ui' (ModuleNotFoundError: No module named 'control_any_sim.ui')
MCCC Version  2024.3.0

**Comment by TitanNano** [comment]
This is a strange error. Are you using the latest version? Please post the full exception which should be somewhere next to your mods. Are you using any other mods besides mccc and this one?

**Comment by vpuhoff** [comment]
The mod version is the latest from curseforge, which is interesting, I did not find any problems with the mod, it works fine. It's just not clear why BE is swearing at him like that

![image](https://github.com/TitanNano/TS4ControlAnySim/assets/2313869/51d2c529-766d-4ac6-9e15-539b42286a68)
[BE-ExceptionReport-OLD.zip](https://github.com/user-attachments/files/15959470/BE-ExceptionReport-OLD.zip)

**Comment by TitanNano** [comment]
You have more than one copy of the mod in your game:
<img width="1154" alt="image" src="https://github.com/TitanNano/TS4ControlAnySim/assets/4500858/eb460d52-1083-40b2-971a-1a46e8e72ded">

**Comment by vpuhoff** [comment]
> You have more than one copy of the mod in your game: <img alt="image" width="1154" src="https://private-user-images.githubusercontent.com/4500858/342446171-eb460d52-1083-40b2-971a-1a46e8e72ded.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzNTIxMjIsIm5iZiI6MTcxOTM1MTgyMiwicGF0aCI6Ii80NTAwODU4LzM0MjQ0NjE3MS1lYjQ2MGQ1Mi0xMDgzLTQwYjItOTcxYS0xYTQ2ZThlNzJkZWQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjVUMjE0MzQyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjM2YjA1ZmQwYTRjMWI2M2U2MzA0M2NmOWMxNTkxYWQwNTExMjNiNzhkMzNmMmFkY2QzODlmNWEyY2E2OWI3YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.KJn3HZb9ZmKIHQFfmdRwOYt0KNKycx9u8LOyvsoMr3M">

So this is normal for script mods, isn't it? package + script

**Comment by TitanNano** [comment]
This section is a bit strange, but if I understand it correctly, it is communicating that you have more than one copy of both the package and the script in your mods' folder. Can you verify that there are no duplicates anywhere in your mods' folder? 

The exception you posted also indicates that the game is trying to load an older version of the mod. The message would make sense of there were more than one version being loaded at the same time.
