### ISSUE TITLE
translate to Spanish

### ISSUE THREAD

**Issue by TitanNano** [TitanNano/TS4ControlAnySim#11]
There is currently no Spanish translation. The following strings have to b translated:

1. Control Sim
2. Don't Control Sim
3. You are currently running ControlAnySim Version {0.String}, which is an experimental preview version! Experimental versions are not intended for normal players, but for testing bug fixes and new features! If you didn't install this version on purpose, you should not use it!
4. Quit Game
5. I know what I'm doing
6. Control Any Sim WARNING

**Comment by richi3f** [comment]
Hey, here are the above strings translated to Spanish. 

1. Controlar Sim
2. Dejar de controlar Sim
3. Tienes la versión {0.String} de "Control Any Sim". Esta versión está en fase experimental. No está dirigida al público general, sino que existe para probar fallos y nuevas funciones. Si no instalaste esta versión a propósito, ¡no deberías usarla!
4. Salir del juego
5. Sé lo que estoy haciendo
6. ADVERTENCIA DE "Control Any Sim"

**Comment by TitanNano** [comment]
@richi3f thanks for the translation! I will add it to the next version.

**Comment by TitanNano** [comment]
Translation should be available in this pre-release version. https://github.com/TitanNano/TS4ControlAnySim/releases/tag/v1.2.0-pre.3
