### ISSUE TITLE
translate to Swedish

### ISSUE THREAD

**Issue by TitanNano** [TitanNano/TS4ControlAnySim#12]
There is currently no Swedish translation. The following strings have to b translated:

1. Control Sim
2. Don't Control Sim
3. You are currently running ControlAnySim Version {0.String}, which is an experimental preview version! Experimental versions are not intended for normal players, but for testing bug fixes and new features! If you didn't install this version on purpose, you should not use it!
4. Quit Game
5. I know what I'm doing
6. Control Any Sim WARNING

**Comment by TezaG78** [comment]
Hi!
I've made a Swedish translation, I hope it helps :)

1. Kontrollera Sim
2. Kontrollera INTE Sim
3. Du kör för närvarande KontrolleraAllaSimmar Version {0.String}, som är en experimentel förhandsversion! Experimentella förhandsversioner är inte avsedda för vanliga spelare, utan för att testa bugg fixar och nya verktyg! Om du inte installerade den här versionen med flit så ska du inte använda den!
4. Avsluta Spelet
5. Jag vet vad jag gör
6. Kontrollera Alla Simmar VARNING

/Teresa

**Comment by TitanNano** [comment]
Thank you for the translation! I will include it in the next version.

**Comment by TitanNano** [comment]
Translation should be available in this pre-release version. https://github.com/TitanNano/TS4ControlAnySim/releases/tag/v1.2.0-pre.3
