### ISSUE TITLE
translate to Italian

### ISSUE THREAD

**Issue by TitanNano** [TitanNano/TS4ControlAnySim#13]
There is currently no Italian translation. The following strings have to b translated:

1. Control Sim
2. Don't Control Sim
3. You are currently running ControlAnySim Version {0.String}, which is an experimental preview version! Experimental versions are not intended for normal players, but for testing bug fixes and new features! If you didn't install this version on purpose, you should not use it!
4. Quit Game
5. I know what I'm doing
6. Control Any Sim WARNING

**Comment by wgiacomi** [comment]
1. Controlla il Sim
2. Non controllare il Sim
3. Stai utilizzando ControAnySim Versione {0.String}, si tratta di una versione in anteprima! Questo tipo di versioni non sono destinate ai giocatori normali, vengono utilizzate come test per bug fix e nuove features! Se non hai installato volontariamente questa versione, non usarla.
4. Esci dal gioco
5. So' cosa sto facendo
6. AVVISO Control Any Sim

**Comment by TitanNano** [comment]
Thank you, I will add this to the next version.

**Comment by TitanNano** [comment]
Translation should be available in this pre-release version. https://github.com/TitanNano/TS4ControlAnySim/releases/tag/v1.2.0-pre.3
