### ISSUE TITLE
Translate to Czech

### ISSUE THREAD

**Issue by TitanNano** [TitanNano/TS4ControlAnySim#15]
There is currently no Czech translation. The following strings have to b translated:

1. Control Sim
2. Don't Control Sim
3. You are currently running ControlAnySim Version {0.String}, which is an experimental preview version! Experimental versions are not intended for normal players, but for testing bug fixes and new features! If you didn't install this version on purpose, you should not use it!
4. Quit Game
5. I know what I'm doing
6. Control Any Sim WARNING

**Comment by Em0lixik** [comment]
1. Ovládat Simíka
2. Neovládat Simíka  (If meant as stop controling it would be: Přestat ovládat simíka)
3. Momentálne používate ControlAnySim Verze  {0.String}, která je experimentální ukážka. Experimentálni verze nebili vytvořené pro normální hráče ale pro opravovaní bugů a přidávaní nových  možností! Pokud jste jsi nenainstalovali tuhle verzi schválně, neměli by jste ji používat.
4. Vypnout hru
5. Vím co delám
6. Ovládat jakéhokolik Simíka VAROVÁNÍ

**Comment by RikudouSage** [comment]
@Em0lixik That's just plainly wrong.
@TitanNano see https://github.com/TitanNano/TS4ControlAnySim/pull/32

**Comment by TitanNano** [comment]
@RikudouSage thanks for the PR.
