### ISSUE TITLE
Translate to Dutch

### ISSUE THREAD

**Issue by TitanNano** [TitanNano/TS4ControlAnySim#17]
There is currently no Dutch translation. The following strings have to be translated:

1. Control Sim
2. Don't Control Sim
3. You are currently running ControlAnySim Version {0.String}, which is an experimental preview version! Experimental versions are not intended for normal players, but for testing bug fixes and new features! If you didn't install this version on purpose, you should not use it!
4. Quit Game
5. I know what I'm doing
6. Control Any Sim WARNING

**Comment by Lyanx1e** [comment]
Greetings from The Netherlands 😃 

I'm a Dutch simmer with a translation proposal:

1. Bestuur Sim

2. Bestuur Sim niet 

3. Je gebruikt op dit moment ControlAnySim (in dutch it's BestuurElkeSim) Versie {}. Dit is een experimentele preview versie! Experimentele versies zijn niet bedoeld voor (gewone) **or** (normale) spelers, maar het testen van bug fixes en nieuwe features! Als je deze versie niet bewust geïnstalleerd hebt, zou je het niet moeten gebruiken!

4. Spel afsluiten 

5. (Ik weet wat ik doe) **or** (Ik weet wat ik aan het doen ben)

6. Bestuur elke Sim WAARSCHUWING

~Lyan

**Comment by ArdentLemon** [comment]
Greetings from the Netherlands too. I agree with Lyan. For 3 I would make it 'preview-versie' since that's a loan word (leenwoord), and a second 'voor' in front of 'maar'. For 5 I would pick the second option, or 'Ik weet waar ik mee bezig ben', but the shorter version is actually more elegant, if not the most 'correct' sentence per se.

**Comment by TitanNano** [comment]
Translation should be available in this pre-release version. https://github.com/TitanNano/TS4ControlAnySim/releases/tag/v1.2.0-pre.3
