### ISSUE TITLE
Game state corrupts when trying to cleanup non existing sims

### ISSUE THREAD

**Issue by TitanNano** [TitanNano/TS4ControlAnySim#22]
When a save game is loaded which is not the one previously played, but containing the same household id (e.g. an older version of the same world), then the mod will attempt to restore the cached state and mess up the game state when trying to access non-existing sims.

**Comment by MickCasanova** [comment]
So far this seems to no longer occur in version 1.2.3 Pre 4

**Comment by TitanNano** [comment]
@MickCasanova great then let's close this.
