### ISSUE TITLE
Turn household sims into NPCs

### ISSUE THREAD

**Issue by TitanNano** [TitanNano/TS4ControlAnySim#3]
Sometimes a player does not want to actively play with all the household sims and therefore would like to turn some household members into NPCs.

Currently, players are not allowed to turn household sims into NPCs for two reasons:

- [x] the `SelectionGroupService` does not know how to remove default members (can be implemented)
- [X] household sims disappear from the relationship panels "household" tab when not selectable.

**Comment by TitanNano** [comment]
User Story:

> I generally start my games with one sim and then find them a life to live and continue through generations but I do find controlling their family annoying because I want to focus on my original sim

**Comment by AsmodeusLang** [comment]
Thank you for the mod _Control Any Sim_. I like it very much.
Btw, I've been searching for such a mod as "Make Unselectable" in the Nraas (a mod of TS3). If this feature is added, I'm willing to give it a try at the first time.

**Comment by TitanNano** [comment]
@AsmodeusLang would you be interested to try out an experimental version of this feature?

**Comment by DoMouse** [comment]
I'm using your mod Control Any Sim and it's very usefull.
I would love it if you'd be able to make a version in wich you can make a Sim in the household an NPC, so i can focus on my main Sim.
My Game is heavily modded, but if you need another tester I would like to help out.

**Comment by TitanNano** [comment]
This is a first and experimental version. https://github.com/TitanNano/TS4ControlAnySim/releases/tag/v1.2.0-exp-household-npc.1

**Comment by DoMouse** [comment]
Game version 1.56.52.1020 anadius repack.

okay, i've tested it a bit, but not extensively.
main issue is when this mod is installed i am unable to save my game, manage worlds or access my library. when hovering over the respective buttons i get a message that "game loading is in progress"
i've tested it with all mods installed and without any other script mods, issue only appears with this version installed. i recieve no LE. 

unselecting/selecting sims works, sims does get removed from household group in friends panel. not sure this is intended, makes it a bit difficult to find the sim again to make it selectable.
can't make selectable when sims is sleeping, but i think that's intended by the game.

**Comment by DoMouse** [comment]
would it be possible to instead of removing the sim icon completely to make it unselectable like pets? or would that cause incompatibility with selectable pets?

Sims is still part of family, checked through mc command center and Shift click shows option
"remove from family"
When removed sim is doing something skill related the skill bar appears and the sims will receive skill gain.

**Comment by TitanNano** [comment]
@DoMouse this version is no longer compatible with old game versions you have to use 1.58. This is why the game always shows "game loading is in progress"

**Comment by TitanNano** [comment]
> unselecting/selecting sims works, sims does get removed from household group in friends panel. not sure this is intended, makes it a bit difficult to find the sim again to make it selectable.

I think this is currently the intended behavior of the game. For some reasons the game also shows selectable sims which do not belong to the current household in this group. At them moment I can only assume that the group is based on selectable sims and not actually the household. But I will look into it.

> would it be possible to instead of removing the sim icon completely to make it unselectable like pets so you can still see what mood the sims is in through the icon? or would that cause incompatibility with selectable pets?

I think this could be possible, but wouldn't this be a bit pointless? If the sims should still show up in the list then why not just not select them? Is there really a use case for having sims in the list but not being able to control them?

> sim still lives at the correct location, checked through mc command center.
> When removed sim is doing something skill related the skill bar appears and the sims will receive skill gain. notifications concerning unselected sim still appear, which i find usefull

Yes this is also what I expected, the sim is never removed form the household and the game treats all household sims as non NPCs, so nothing should change here.

**Comment by DoMouse** [comment]
I've updated the game and i am able to save again. hadn't noticed that there was an update available. my apologies.
as far as i can tell everything is working as intended.
persistence through loading zones and restart. autonomy, skills, relations, work, money.
since this is my first time testing a mod, do you have any advice further as to how to test this version?

about leaving the icon the list. with pets you can see what it's mood is through the color of the icon. I thought that might be useful so you can still keep an eye on the mood of the sim. but i suppose you can also see the mood when conversing with the sim.
It was merely a suggestion and if you consider it redundant I apologize.

**Comment by TitanNano** [comment]
>  It was merely a suggestion and if you consider it redundant I apologize.

No need to apologize. I'm simply trying to discuss the best solution. I see your point, but I also wonder what most players want from not being able to control a sim. 

>  since this is my first time testing a mod, do you have any advice further as to how to test this version?

Just try to play as much as possible. Also, try to do many varying things. For example travel with unsetectable household members or go on vacation.

**Comment by TitanNano** [comment]
There is now a second experiment: https://github.com/TitanNano/TS4ControlAnySim/releases/tag/v1.2.0-exp-household-npc.2

**Comment by TitanNano** [comment]
Household NPCs will be available in v1.2 https://github.com/TitanNano/TS4ControlAnySim/releases/tag/v1.2.0-pre.3

**Comment by SimKrazy** [comment]
First off thank you for your Control Any Sim mod. I love it! I was one of the ones who commented about household members being NPCs. I don't get a lot of time to play the game these days, but when I do I would be willing to be a tester if you still need some.

**Comment by TitanNano** [comment]
@SimKrazy You can take the latest pre-release version for a spin and if you encounter any issues, let me know. https://github.com/TitanNano/TS4ControlAnySim/releases/tag/v1.2.0-pre.3

**Comment by SimKrazy** [comment]
I manage to do about 5 hours of testing with no other mods installed. I played with every age group as NPCs. All regular sims no occults.

I noticed that when on both  vacation worlds they take great care of themselves even the toddler when provided food. When on the home lot not so much. I was living in an apartment. I haven't had time to test other apartments or regular home lots yet. If you assign any NPC a bed they would not sleep only take naps and mainly stand around until time to work or go to school. The toddler would not eat or sleep just pass out on the floor all the time, but once you unassigned the NPC beds and reloaded the lot they seemed to take a little better care of themselves and not stay in the red the whole time. The toddler would actually go to sleep in the bed and eat.

I hope to do more testing in the near future on different lots and more apartments to see if the same thing happens.

**Comment by TitanNano** [comment]
@SimKrazy thanks for the thorough feedback. I guess on a home lot NPC household members mostly behave like normal NPCs and by Maxis definition NPCs on home lots are usually guests and will usually leave after a couple of hours. So I assume they never really setup autonomy for them to be focused on keeping their needs up. NPCs on vacation lots on the other hand have to take care of themselves as the player is able to take along friends and expects them to take care of themselves. This is all just guess work on my part. As NPCs are now possible, I'd say we close this issue and open a new one for tweaking NPC behavior.

**Comment by SimKrazy** [comment]
That sounds fine to me. I will continue to test when I can. Is there anything specific I should be looking for?

**Comment by TitanNano** [comment]
For further discussion see #24.
