### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by asiamuh** [TitanNano/TS4ControlAnySim#38]
Can no longer find the option to control a sim in my game. I have unzipped the file and installed both the script and package file, but when click an npc sim and go under actions the option to control a sim doesn’t come up.

**Comment by TitanNano** [comment]
@TitanNano are you running the latest version? In game, you can open the cheat console and type `canys.version` which should print `1.2.2`

**Comment by asiamuh** [comment]
It says I I’m running version 1.2.1 but I installed version 1.2.2 and placed version 1.2.2 in my mods so I don’t know what’s happening

**Comment by TitanNano** [comment]
It appears as if you have two versions of the mod in your mods folder.

**Comment by asiamuh** [comment]
Thanks that was it
