### ISSUE TITLE
Control A sim action not there.

### ISSUE THREAD

**Issue by mela2cool** [TitanNano/TS4ControlAnySim#64]
Hey, I guess I can speak for most of the people with this issue. Most of us noticed this mod probably needs an update because of the new infant update.. Now I downloaded this mod recently and there's no option in 'Actions' for sims. A lot of people are also having this problem and we just need an update :(!! please

**Comment by TitanNano** [comment]
Do you see a debug.log file next to the files of this mod? If it's there, please upload it here, if not, then the mod is not properly being loaded. Has this mod worked for you before?

**Comment by mela2cool** [comment]
I do not see the debug.log file, and I've never had this mod until I tried it a few days and it didn't work

**Comment by TitanNano** [comment]
This indicates that the mod is not being loaded by your game. 

Where exactly is the `ControlAnySim.ts4script` file located on your computer?
