### ISSUE TITLE
yea its about the control sim mod...

### ISSUE THREAD

**Issue by plsbringbackthemod** [TitanNano/TS4ControlAnySim#65]
hello !!
i know people ive been telling you about the CAS mod not working anymore and yea same. i miss it way too much, as in i dont even wanna play the sims without it

do you think you will update it ?? do you need any infos to do it or anything else ??

tysm, have a good day !!!

**Comment by TitanNano** [comment]
This is a duplicate of #62 please provide the information that was requested there so I can investigate potential issues.
