### ISSUE TITLE
As of 1.96, Moving Sims Out With Mod Installed Leaves Moved Out Sim Stuck In Household & Off Lot In Limbo

### ISSUE THREAD

**Issue by NateTheL0ser** [TitanNano/TS4ControlAnySim#66]
I had a sim move out, in two different ways (via Manage Worlds and Phone), with the mod installed, and the sim was stuck in the sim panel, still considered part of the household, but was off lot and could not be interacted with or brought back. This issue resolved upon removing the mod, and sims became able to move in and out without issue. An update is probably needed to fix this.

**Comment by k-schmitz** [comment]
Hey @NateTheL0ser may I ask, did you have this issue of moving out Sims getting stuck, while you were controlling a Sim, or was no Sim currently controlled when moving them out and the mod was just simply installed but not in use when you experienced this issue?
