### ISSUE TITLE
Unable to switch active sim

### ISSUE THREAD

**Issue by TitanNano** [TitanNano/TS4ControlAnySim#7]
Sometimes it is not possible to switch the active sim after loading a zone.

**Comment by TitanNano** [comment]
User observations:

> 1)  After a Reload, going into this household only 1 was at home, so that is the Sim selected when loading household...
> - Then, only 1 Sim will allow selection for control in the UI - the other Sim cannot be selected in the UI below, nor can it be made to select control from Actions menu.
> - But, if I click the other Sim in the UI, even though it does not show it being selected, it does show menu options to converse etc with the opposite Sim shown in the UI as selected.
> In other words... it is operating correctly, but the UI does not change the selection box around the Sim... the same Sim remains selected the entire time.
> 
> 2)  After going back to manage worlds, then going back in to the household without selecting any particular Sim (both are at home now)... No issues... control in the UI can be changed back and forth.
> 
> 3)  After going back to manage worlds, then going back in to the household by selecting a particular Sim to control first, all seems to be working fine still... no issues changing control in the UI, but again, both are at home.
> 
> So far, it seems that the UI doesn't want to change the selected Sim controlled if one was not at home when the household was loaded, or if other Sims were in control who do not belong to the household.  These are the only times I think I have had this issue.
> It may be conflicting with WickWhims Mod, as well, if anyone uses that - I just don't know what is related in the exception report it created.

**Comment by bruceiwayne** [comment]
You mentioned it should not conflict with WickedWhims... I asked just out of curiosity if they had tested it and it isn't a conflict, but they saw what was making that error and will correct in their next update.

**Comment by TitanNano** [comment]
@bruceiwayne this issue should be fixed in this **preview version** https://github.com/TitanNano/TS4ControlAnySim/releases/tag/v1.1.0-pre.1

**Comment by bruceiwayne** [comment]
Awesome... I will try it out this evening.  Thanks!

**Comment by bruceiwayne** [comment]
Hi Titan,

Great news!  In all that I have tested so far, it is working great now.  I haven't found an issue.  Thanks for your hard work!
