### ISSUE TITLE
Throwing LEs on loading

### ISSUE THREAD

**Issue by VictorHFerrari** [TitanNano/TS4ControlAnySim#72]
It is throwing LEs whenever a lot is loaded since the 1.103.250.1020 (For Rent) patch.
According to Tmex's Better Exceptions, the problem is in the game_events.py file.
![image](https://github.com/TitanNano/TS4ControlAnySim/assets/48529552/d6a2addd-d7dc-4a59-afe5-58a29649e0e8)

Been playing with it for several hours and the core functionality works just fine. Just a heads up in case _there is_ an actual major problem.

**Comment by TitanNano** [comment]
`game_events.py` is part of every major game event as it is responsible for making these events accessible to the mod. This doesn't mean it is responsible for the exception.
