### ISSUE TITLE
Moving homeless sims causes exceptions

### ISSUE THREAD

**Issue by Lizziguin** [TitanNano/TS4ControlAnySim#76]
(Sorry for posting on the help instead of issues) I'm testing on a new save without any mods but the control any sim and Better exceptions. I got this Exception and then I couldn't see anything on the gallery in build mode. However, I don't know if it was a fluke glitch or what because now I can use the gallery again (I think it might be a fluke situation). I deleted my L File's from what the Twistedmexi discord server told me to do and so far that issue hasn't popped up again. I'll update further with more testing. 
<img width="1073" alt="BE control any sim" src="https://github.com/TitanNano/TS4ControlAnySim/assets/162646782/ed80fea7-2b94-4da8-871f-37c27dd4c3aa">
<img width="1278" alt="gallery bug control any sim" src="https://github.com/TitanNano/TS4ControlAnySim/assets/162646782/bc775dc7-df35-46d6-acbf-50cfe71fd859">

**Comment by jwidanka06** [comment]
[BE-UIExceptionReport.zip](https://github.com/TitanNano/TS4ControlAnySim/files/14535910/BE-UIExceptionReport.zip)
Hello, I have uploaded a copy of the actual report from above.

**Comment by jwidanka06** [comment]
Hello, 

So playing in a save with only ControlAnySim and BE I received the following better exceptions report. 
[BE-ExceptionReport.zip](https://github.com/TitanNano/TS4ControlAnySim/files/14536200/BE-ExceptionReport.zip)

I hope this report will help you in your efforts to update Control Any Sim. I love the mod and would love to see it updated. I noticed that when you join a sim that was the initiator of a control and move them into the controlled sims house the control ends. This also happened when a vampire sim went from normal form to Dark Form. 

Thank you

**Comment by TitanNano** [comment]
@jwidanka06 these are all exceptions related to a sim that is asking another sim to be their roommate or moving someone in from the gallery. In both cases, there was a sim without a home involved, most likely a controlled NPC.

Can you confirm that this is what you were doing?

**Comment by jwidanka06** [comment]
> @jwidanka06 these are all exceptions related to a sim that is asking another sim to be their roommate or moving someone in from the gallery. In both cases, there was a sim without a home involved, most likely a controlled NPC.
> 
> Can you confirm that this is what you were doing?

Yes they were a controlled NPC, however, I was just using the mod to take control and then turn them into a household NPC. The one I created in game the other was not it was a gallery sim. The other was triggered by taking the sim without a household and adding them to my household with the mod. I do hope I’ve explained this well.

**Comment by SandraBochmann** [comment]
> @jwidanka06 these are all exceptions related to a sim that is asking another sim to be their roommate or moving someone in from the gallery. In both cases, there was a sim without a home involved, most likely a controlled NPC.
> 
> Can you confirm that this is what you were doing?

Hi, is there any chance that this Mod gets a proper Update for the latest patch? Now people are using it on their own risk

**Comment by TitanNano** [comment]
@jwidanka06 I have tried to reproduce this exception but upon further investigation I can not see how this could occur in a working game. 

Each time the exception reported that there was no active household, but this should be impossible, and the game code expects as much, hence the exception. I also don't see how the mod could cause the active household to be unset.

I'm strongly inclined to rule this as a bug in the game and unless you are still able to reproduce it, I will close this issue.

**Comment by jwidanka06** [comment]
> @jwidanka06 I have tried to reproduce this exception but upon further investigation I can not see how this could occur in a working game.
> 
> Each time the exception reported that there was no active household, but this should be impossible, and the game code expects as much, hence the exception. I also don't see how the mod could cause the active household to be unset.
> 
> I'm strongly inclined to rule this as a bug in the game and unless you are still able to reproduce it, I will close this issue.

I have just been playing and trying to reproduce it in my own game in the same way and have yet to be able to get to cause the same error. So, I am unsure as to what was actually happening before though it was before the most recent game patches so that could have something to do with it.

**Comment by TitanNano** [comment]
> I have just been playing and trying to reproduce it in my own game in the same way and have yet to be able to get to cause the same error. So, I am unsure as to what was actually happening before though it was before the most recent game patches so that could have something to do with it.

Alright, I will close this issue then, but feel free to post again should you encounter the exception again.
