### ISSUE TITLE
Mod folder can't be resolved on macOS

### ISSUE THREAD

**Issue by Tgate0224** [TitanNano/TS4ControlAnySim#93]
I get this last exception when loading my game after updating to the new version of the mod. I removed all old files and replaced them with the new mod files when updating. Any help is appreciated.
<img width="708" alt="Screenshot 2024-06-12 at 3 49 18 PM" src="https://github.com/TitanNano/TS4ControlAnySim/assets/172542003/01fb3adb-91fe-4b53-890e-35d12c75428a">

**Comment by TitanNano** [comment]
@Tgate0224 thanks for the report. Are you on macOS?

**Comment by Tgate0224** [comment]
> @Tgate0224 thanks for the report. Are you on macOS?

Yes I am

**Comment by TitanNano** [comment]
@Tgate0224 could you please try this version? [ControlAnySim.zip](https://github.com/user-attachments/files/15816753/ControlAnySim.zip) (you will get a warning that it's a preview version)

**Comment by Tgate0224** [comment]
This version works fine! No exceptions and I can control and uncontrol sims outside of my household with no problems.
