### ISSUE TITLE
Controlled NPC not greyed out after leaving lot autonomously

### ISSUE THREAD

**Issue by amethystlilac** [TitanNano/TS4ControlAnySim#95]
When a controlled NPC leaves the lot autonomously, they still show as active at the bottom of the screen.

This lasted until I directed a second controlled sim to leave the lot. Then they both were greyed out.

I assume that it would also correct itself if I travelled or otherwise reloaded the lot, but it's a hard situation to reproduce.

**Comment by TitanNano** [comment]
@amethystlilac this has been fixed and will be part of the next version. You can test if the fix works for you with this preview version [ControlAnySim.zip](https://github.com/user-attachments/files/15840701/ControlAnySim.zip). (you will get a warning that it's a preview version in game).

**Comment by amethystlilac** [comment]
Thank you! It does seem to work.

**Comment by TitanNano** [comment]
Good to hear. The new version will be on curse forge and MTS soon.
