### ISSUE TITLE
Broken for Mac players

### ISSUE THREAD

**Issue by mkelley123** [TitanNano/TS4ControlAnySim#96]
I get an LE upon load with this mod in my mods folder. I play on a mac computer. I've tested with only this mod in my mods folder and a lastexception.txt file generates upon loading into my vanilla test save. I put BE in the mods folder with it and I also get a BE error with the lastexception.txt file. 

I've attached both the lastexception.txt file. Let me know if there's anything else you need from me. 
[lastException_63854008896.txt](https://github.com/user-attachments/files/15830305/lastException_63854008896.txt)

**Comment by TitanNano** [comment]
Thanks. This has been fixed and a New version will release soon. #93
